Added pilot buttons that switch to a panel that displays pilot profil…
oneleif/economyManager pull request #18
Opened 2020-05-23 09:35 UTC by pseudowalrus

…es. Uses a prefab & scriptable objects for pilot data. Buttons are created at runtime (similar to mission buttons).

2020-05-23 20:34 UTC, ambid17 requested changes
Once we get designs from Fardeen, you will need to make the `PilotsProfilePanel` responsive rather than laying the elements just out on the page. However for a first pass it works well for now :D

2020-05-23 20:34 UTC, ambid17 commented on Assets/Scripts/PilotButton.cs
> +    //public GameObject buttonObject;
why is all of this commented out

2020-05-23 20:34 UTC, ambid17 commented on Assets/Scripts/PilotsManager.cs
> +		pilotProfilePanel.GetComponentInChildren<Button>().onClick.AddListener(delegate { ClosePilotProfilePanel(); });
just hold a reference to this button, in case the UI changes

2020-05-23 20:34 UTC, ambid17 commented on Assets/Scripts/PilotsManager.cs
> +		pilotProfilePanel.GetComponentInChildren<Button>().onClick.AddListener(delegate { ClosePilotProfilePanel(); });
remember to RemoveAllListeners() first

2020-05-23 20:34 UTC, ambid17 commented on Assets/Prefabs/PilotButton.prefab
> +%YAML 1.1
you need to set the anchors so they scale

2020-08-30 21:23 UTC, maxwellpark commented on Assets/Scripts/PilotButton.cs
> +    //public GameObject buttonObject;
It was redundant. Removed it.

2020-08-30 21:29 UTC, maxwellpark commented
Considering making a game-wide UI generation utils class, hence why the PilotsUtils class is unfinished.

2020-09-01 22:29 UTC, merged